### ISSUE TITLE
spelling & grammatical errors

### ISSUE THREAD

**Issue by ryanmeinzer** [learn-co-curriculum/programming-univbasics-3-conclusion#3]
"Very similar to IRB, while the program is stopeed, we get access to variables and methods and can use them. "

should be

"Very similar to IRB, while the program is stopped, we get access to variables and methods and can use them. "

and 

"We'll be exploring Pry a few lessons."

should be

"We'll be exploring Pry in a few lessons."

**Comment by maxwellbenton** [comment]
Hi @ryanmeinzer,

Thank you for spotting these and taking the time to provide feedback. We've updated the lesson these errors are in (https://github.com/learn-co-curriculum/reading-errors-and-debugging-introduction) and believe this issue is now resolved.

Thank you for contributing to a Learn lesson!
